#!/usr/bin/env python3

"""
A program to check the release numbers for consistency.

Release numbers are found in:

* the latest git tag
* setup.py

Check that the latest tag number and the numbers in setup.py
are consistent.  Will exit with an error code if not.
"""

import sys
import os.path
import subprocess


TagConfigFile = 'setup.py'


def abort(msg):
    delim = '*' * 60
    print(delim)
    print(msg)
    print(delim)
    sys.exit(1)

def setup_tag():
    """Get the configured tag number form t\the setup file."""

    # assume data doesn't exist in file
    version_line = None
    download_line = None

    # read the expected tag number lines
    with open(TagConfigFile) as fd:
        for line in fd:
            line = line.strip()
            if line.startswith('version='):
                version_line = line
            if line.startswith('download_url='):
                download_line = line

    # make sure we got both
    if version_line is None or download_line is None:
        msg = (f"Can't find tag numbers in {TagConfigFile}:\n"
               f"version_line={version_line}\n"
               f"download_line={download_line}")
        abort(msg)

    # extract the release numbers from string, check the same
    # version_line=version='4.0.5',
    # download_line=download_url='https://github.com/rzzzwilson/pySlip/releases/tag/4.0.5',
    version_tag = version_line.split("'")[1]
    download_tag = os.path.basename(download_line.split("'")[1])
    if version_tag != download_tag:
        msg = f"Different release numbers in {TagConfigFile}: '{version_tag}' and '{download_tag}'"
        abort(msg)

    return version_tag

def latest_tag():
    """Get the latest tag release number."""

    p = subprocess.check_output(['git', 'describe'], text=True)
    try:
        (tag, _) = p.split('-', maxsplit=1)
    except ValueError:
        return None
    return tag

def main():
    # get the latest git tag number
    git_tag = latest_tag()
    if git_tag is None:
        abort('No release tag number set!?')

    # get tag numbers from setup.py
    config_tag = setup_tag()

main()
