#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
A tile source that serves OpenStreetMap tiles from the internet.

Uses pyCacheBack to provide in-memory and on-disk caching.
"""

import os
import glob
import math
import threading
import traceback
import urllib2
import Queue
import wx
from wx.lib.embeddedimage import PyEmbeddedImage

import tiles
import pycacheback

# if we don't have log.py, don't crash
try:
    import log
    log = log.Log('pyslip.log', log.Log.DEBUG)
except ImportError:
    def log(*args, **kwargs):
        pass


# tiles stored at <basepath>/<level>/<x>/<y>.png
TilePath = '%d/%d/%d.png'

# the 'pending' tile data
def getPendingImage():
    """Generate 'pending' image from embedded data.

    This file was generated by /usr/local/bin/img2py
    We used to have a separate image file for this, but this is better.
    """

    return PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAABYlAAAWJQFJUiTwAAAAB3RJTUUH3wQKCS4x4IlwZwAAIABJREFUeNrt3Xm0ZWdZ"
    "5/Hv875773POPXe+VbfmSk1JVeaBVEigE1sSW2JkUGiMtou2GyQucWiwEehFI9LtWqKybOmO"
    "dju0tgpKRECZFIJghxBCICQhY1VSc6rq1ninc885e+/3ffqPve+tSiVFWlFTLp7PWnfdqlPn"
    "nrPrvuf9vcN+97tFVTHGfGdy9iswxgLAGGMBYIyxADDGWAAYYywAjDEWAMYYCwBjjAWAMcYC"
    "wBhjAWCMsQAwxlgAGGMsAIwxFgDGGAsAY4wFgDHGAsAYYwFgjLEAMMZYABhjLACMMRYAxhgL"
    "AGOMBYAxxgLAGGMBYIyxADDGWAAYYywAjDEWAMYYCwBjjAWAMcYCwBhjAWCMsQAwxlgAGGMB"
    "YIyxADDGWAAYYywAjDEWAMYYCwBjjAWAMcYCwBhjAWCMsQAwxlgAGGMsAIwxFgDGGAsAY4wF"
    "gDHGAsAYYwFgjLEAMMZYABhjLACMMRYAxhgLAGOMBYAxxgLAGGMBYIyxADDGWAAYYywAjDEW"
    "AMYYCwBjjAWAMcYCwBhjAWCMsQAwxlgAGGMsAIwxFgDGWAAYYywAjDEWAMYYCwBjjAWAMcYC"
    "wBhjAWCMsQAwxlgAGGMsAIwxFgDGGAsAY4wFgDHGAsAYYwFgjLEAMMZYABhjLACMMRYAxhgL"
    "AGOMBYAx5p9SYr+Cc4+IXAW8HPg1Vc3rxwR4K/BBVT38wh7fR1ex+Wf+CLf5KZaf9wg93UFn"
    "9m59/C/mrPT+mX3WVNV+C+deAKwGrgcuBFLgM8CPAgeBDPgFVQ0v2PFN3vh2xu+9lN7FXTTt"
    "4hod2rrA4IrHyMPf6v13HLVStAAwf7/Kvwz4A+DtqvpI/dhfqerL6z+3gdvrENj7T398Tw6z"
    "4V//IdluRUYKGJujaE3jXcrQqt2QQmSKInxJH75jn5WoBYD5uwXAfaq6HUAuu+wIQ0MnuPfe"
    "w1x11QPcd9+7VHW+ft7vquob/8mPb+Wv/hDL7rqYhf1b6R9KyWSa1soF2tsOUvZzfARNAi5R"
    "onTI0i/pPX/4mJXsuckmAc+tyv+TwE/Wf341Gzd2+fKXt3LeeZcyPPyDXHDB2057evw232uV"
    "iHxeRO4VkdtFZOD/6wcndm1DmscZv+g+RrbuJYw0mO5lTO1fR7c3SlE2wFcfrTQdRsIt8pJX"
    "vU2ue9mLrYQtAMy3drmq3gegqh/n8ccPiQAvuvYYrVbOjh0fqivvOuCJb/O9XlZ/fRZ4NbDv"
    "eQLjh6V97ZcYPnKCpADVkoG1T7Ny+zcY33YYn3TpHlvB7NFNLMy0KIqAlkpIhKApce41cs2r"
    "3iVXXrPditkCwDy7gr0GGBaRN4vIS0Tk54dbOzZe9xewecWHLvB3fvIkcJuIfHTkSvYBnxOR"
    "Hzi9Ra+/N+szBojIRP39x057nheRn6Vqpnuq+p+BrcCEiFxezzGcflwDIrIduIkNV92DH2pA"
    "SwBQAnkZyFrTDI3vZ2DoAOgcvfn1FPkE/aCURYG2c9zoAmUinHCjVtrnDjsN+MJX/BawB/iN"
    "89/GrXNPcWsxD+PbYfVNELqw+hUQG1ztIlePXw3ttfC1N/Lm+Z38i7rrHoEPAQLsBr4gIu8G"
    "dorIZuB/i8it9UTi14DzgPcAvfrn318fzo8AbxWRlqqWIvLHwBXAONm2PpOd/0ZHE4gKvmo8"
    "vCjqHFkq+MGcrH2Abn+U1uBJYqmAI0hJXDlLOTPCvns/KyKbVHW3lb71AL7jqWoXuMwP8kur"
    "b4Hzb4PNb4DJ66rKD6AB1t0MI5dAYxzKBRi5nDcB71XVDwJ76zD5LmAlcANwE5Cr6i7gfOB7"
    "RaQHLAPWA6P1Vwf4d8D3Au+tG4XfFJHlwL8BfltVV7P2lg9wcs5R5CWSJItHTxBBNKJJRNo5"
    "6bDSHjtGCIJ4R4zgIkiIrH/J/6n/2zdYyVsAmFMhMLXmB6sKrwGyIZAzSibmMLAK0OqrvQWA"
    "++p//kb9/VeA43UIvA74ZP34HDADNICfqs8kjAEPAitUNVPVz6pqB3g38OPA79RDhA/IwG9d"
    "y/CTfRotUHGIRlAlAqKKU0WdIAQ0Bnzq8CixnqcsA5RR9ZPv2FUfT2qlbgFgTjNwXl25gbIL"
    "vll36AHxIPLM5/uqCvVO60WcAK4Bfqoe33838Kcisg3YDzwE/C/g4yKyvm7pF1T1yBlh9F+A"
    "eeBVdY8Awp+8kpMHIQ8RUYVwqnI7oKRq4WPVD0GiQpLgHDhX1fcyLIZVAUxaiVsAmNMUJ+rK"
    "7mDuUbj7tdA/Ab0j8PB7IJ9/5vP7J8lV9eBpD/05UKrqnwJfBwpV/bN6XP8ZVb1BVX8CuAv4"
    "XeDpulfwXH6vnlf4ZZHbr4J7evSDVJUfiHVUJYB4hxMhAt67qjcgDkSrT5cIUjoe/shE/dq7"
    "gTVW4ucGmwQ8R3Sn+LJ4XqIB0mWw6tWQDELoQMhhfgeMXXmqR3Do0/wO//0ZL/HmuvsO1em9"
    "0bpFf/cZLfwNIiJarQD75bMczpuBX1FVTeVfvTrGcjau3FJVdq2a+SoIRJC6GRHnkRhR7wCt"
    "egE+JYaC/sxuVf1E/drfBcxaiZ8bbCXguVIQIrds/yM+2ZioqpdvQOjXwwJXDQE0gMtgx2/Q"
    "PfwJRlS1eOZr3JbCDg8bzvIue1D9Qu95juN1wIfruYEjIvcO43/1BzhveDUT8wsUiUCEGBWX"
    "VEHgnUc0nlqapIp6h0RFVZibvl13frpvpWwBYM5e8X7cj3DNhe/mjeOXV5N+zxqvNWDXb8OB"
    "D3Ojqv7Ns1/jlg9BGAD3PdXIXM4o3H5P9c6Vz3Mc1wGvU9W3PPNxhBW//v0M7b+Sof0nUe+I"
    "gHP1mgAVvIMY4tJjAFF36jf+5FNWwjYEMN/aZJxhy9jPcedD17Jh8nq2DF8K6TAUMzD/BOz/"
    "CHR28J+AwbO8Rl/569cLNz8I0nr2P+vztsKqeg9wz7MfR+EtnwA+IaO338iyfdcyumuW4Dwx"
    "RJLEE1Vx9foAV88itFv/14rWAsA8v+Ovgr13wqfn7tE7RGQohb3LXsNYYxyak7DudfD4f2UV"
    "cOBsL/Lr1Sk2+cc8UJ1+8+eBz8v4772U0X03M/7EUVSrSb+oWk0KqhK0x8yxa+WyH1IariQE"
    "JQlK4RyAfuPPvmjFbgFgKo/Nwto51TvqlnhuuClfWvl9vKK9EvBw5PMA/DWw/O/3Fmc/6XPr"
    "rXJBobxCI/ucstsNceCO3//WG4/oiTfcLS/97o1Mvfhq+v2CVXNTuIWSsg4D7Y3RdFspNKPo"
    "ZjifkEchS2boFisACwALAAOwAS566tSCHgB6fcaSFsQSvvZWyK8AYL2q/tbfcYbBr0k+9cQl"
    "G0j/6D/Ku/Ly2QtxNjbxO2dphYItrkE/XyC95dXSl4TpRsaUi+zrl+ybc+z9wh26dFLyqqEv"
    "pvfPfu0o/qIZHo5bGbgc1rGfON8nbSzQ77VJYw5pxKddItUEYpYtWKlbABhARNa+Fl7+KPzt"
    "MwpngBe1VsLhv4K8DbwJ+DD+bSLtABfqaZcENyA0eNnI2Vr+H3kZK6+9lD/2kdcjZ5S7onsD"
    "DzTgSCiJeKSR4LOMpgjLUCZjwcUiSCvALa+V2C2Z6hY8eWKakYnGfPu4ZEKjs3O493t+ds9N"
    "61h13mFaCzlZs6DIPUmaEIsu0mgBHiG3krcAMJWVHwPZdlrXXkQ2b7uFTEtI2lRr86p2f9/l"
    "cDnwKYW+wIrFgtzK0bm3QO+t1UlDOXUWQBBPsuub3L75Em4RrX5m6b0COpUzj6JZteowSkD7"
    "gdjyaIgUGokOfBlJfEIjiawYSZjsDNAfT8mOHz0UWH9le7Y/3EF5jJlHlNhuMzBRQmggMYIf"
    "pD/dpNmO5PmwFfsLz1YCnhseD/C+R06bvBsd4R2j30WuJSy7Dra8GpIHAfhKCTHA/wjwAYW+"
    "Qq/6Ll3h5XdTnSVw9ZdAdFAlhTzHBKGkyIl55vIe0UFMAsEV5FmBikLm8WlC4oXYSlAP0Tky"
    "l+LXjzEwOYw/f/ipjOIjkbTRRnQsO/KVTTz9zXFCv0SSiEtLSPs02h0iik9sA1HrARiA+uKc"
    "u0Xkq3Xrn27ZxOvYRqvqocP4FTD7AIenduiRPxDZJJBoteafxefcwNPNi5jZ5iC5h+W/uYcV"
    "O+tiDquX8W+Zeo4WQOAP7qI13+C8vIdrjTLdn2fdcJN9WZO8V9DwGbl4JEtxXpAyohqQWBJz"
    "RdXhzx8mXb+G1Z9/cOcx/LX93C+fas3PJd1+ERnMShZKR+oj3jk8kSC2AMUCwJwRBIsr+96w"
    "6mZKGtWy34feB9P3AXOcdUFNAH0xxzPhOEBzK3vv/AXVOxf//eNvk5vnniMAosJNl3H4Yw/R"
    "aSUkkqPdHj7vsMY5hkPOTNKAxhCzWUaZNCl8Qp46fBC8QBkh7yihnGF+TXN3+XR3pWPL1Xmx"
    "6zMrefqLPdbe2CPNUiQIMfZxqYMQrcRtCGCew0VbeGVnM0MaoPMkTO+jujwncNfzhkid6qOc"
    "McnmeK4OAADdHofGhakx5dCEcHxyiB2NhIWhlD3thOkGzPU7rDx+hInjR9kaS6KUxNTj+yWx"
    "e5KFItAcTBm+4gLWrh2/ZxDXHC/Ht+9rFAtbmHo0RUUoXYJLHdElBO+tpC0AzJnjcRHnHNcn"
    "m6pTdRrqWv3Vavx/1p+rK/5d4N8H+na4XUQ+IiK3LvUSNpDIGdfii6InZ+iWXfKZGULooW2H"
    "Wz7OgYEWx5OEXa0WRwYb7B0YZKrRZo+mJKWDPKc8cpTje3ew4uROmo02yckuvfXDjC5vfCww"
    "4Ub7bnQfc/tXUJ7MEI0Eqg1E7JNnAWCe03VrXkQnq/foHbwAll8I8j+B6lLaRYWDANWdQv4a"
    "kne+luY9v0b6wCTS/xyX8FFeI8v4Ezciu/ZP0do6yFdVmUDqxKiv6dt/lOO7pxl88jirZrqE"
    "xKOUNEsojp9km3eUrQbdsVG6AxmHQ5+ToaBQ6HbmmY05MxoZmJ2m8JA1hXLzcsacvzdl280N"
    "LrjpAK3lBVnqSH0CDoKIFbXNAZhnWzG+gWKhbvhjARf+NBzfDo+8izaQu6rqviOF2b3A+9fR"
    "OHYtsrpdTRY2V0Dv7VXpLrseLn4rG995G8s6j7JOVZ+xB4D84i+618695xenO2x0SkTwLiBe"
    "iEWXooh470gaTbIFR5iewhXK8MQqJESmhwaYjWO004ypvEepkSZKT1MkQiQda5DSpnACGoku"
    "IkGx+m89APOcQujxzJN1EaZ3APBBgNfD/Q/Bz7wX+u98E41jH0aYAK9VYFz9Pth6E2y7Cbb9"
    "BPSPQKfHEBexS0TGTn+zH/ur96zXlObEGFODA8z6SN6Zw5cdpFggjY6+ZjS0RwgLxNnjjHmh"
    "32qTiXJo9Qra67bRX7aWrNlmoNkkDLRIE4cb9CQU/YDPHGk96y+xulTYPnnWAzDP6dDsY/jw"
    "8lPpPP8UPP1p4H3cLNfILhxzm27jsjICdwP3wkABG369njMQmLyx+rMGKGapBgu/zTg/y1Mi"
    "skVVT1D1MNY2m8QNA/RiRjFQ0oo9ym6XzCfkK5dxxJcMuoIySSBNGckyjhYF2hhkz5H9XNrP"
    "2TAwwOE8p5EHGo2U6X6X5jLhkvn+7r8hWV2tWbRG3wLAfGuq+tXtL5Imj5M3zycDaK6hmrpz"
    "wM+xkf8A638YQg8mt1e7BA9fCKqQHyVc02LvocfIjqSM5BczNLAWJq+AI68ERhgbu5qnReRH"
    "VfXPg2NNJvRcxGtO5oQ0GyEv5tDhjCEn5LGHSgOngTi5jD1ulGEgKUt2xwVuJEU782wqPVok"
    "nMgXuKwXOLBsNffteXqhiaQLFL1yaWkS0fqe5wjbEORcLBSRD77xnVz18PVsS07rBTz2AejP"
    "wpqbYdOtoHFpk2BiBP0sJ9zd9O9/mHv7fe4fG+HaNRu5pv0GBrNLaPanqs1Gswn4+ltgfgW6"
    "aZIvbbqfRyaHmHEBrxFJGujMDI2J5ST5PKUGIi3SXAg9QTTDuQb+43/JT119NdmqVdUxPn6U"
    "ZGQ5ZdZCn3wUv2oN+lD+LwNsgANTpz5oa1cIgH7h93tW2hYA5tkB4Net5dD1P8vC3ss5T8rq"
    "cd+stgkTD1o/lu7l8cZeDvS/Rh4OIV64a+U4B0WRplAcmGIjnuv0aprNMZwoTjPKE5+l9+Xv"
    "5ntW5Tw69AkObngpofg6e1ZO0Es90unQbrUpguAIhMYAaUeJJ7usnu/QHpxg1+e+yMgNN/GR"
    "PGVLNsm0Kwh06fU6JHtySFPy/ftfOszghn3ksdoLwCXV9mEqTu/74KettG0IYJ49DAgicsP9"
    "v8MXLnsNux/fzMbRjaf2CNSy2iOwBOQbHFn+FE9IicRxRBLW9CKbsmr6LZkcR33JgeIxSJTE"
    "l3jn0JV9Fo4qcfmTHFw7wWP6BOKHcRQ0EfrOE0MgikcLB05BGkQtKBsN5sqcEeCtCx1+aXgD"
    "USNOSnKJ5I0mvaJg6OQs87RXdynCAF4cWabEev/AslTAAsACwJwlBB4XkcsP/xZ33fBSdrmt"
    "JMfHGC2GaKRNwug880c/gYtz9FiNjwEtOvRDQXADZKoUmhKTQZo6Qz90iOooY0rmBJcpOnwF"
    "JLtRn5LhEQkUecCnik88guBRSknJgkM14tujHMqVtAdeVQ/f8sNyf15wUd4nySC6hLQMlE7p"
    "9+N4SrlsFn9IIYsUUcAFMu+qcxbGAsB8C5Ovn54+cs9fforX8ylkxSSd8VHmul2Sew4yWYbW"
    "Vy7e3L135TJGooPWOJlTtDdDLgPogieGDieHE5KhUdIy4GKXvFygTIfpPfjvHReuim7VKgrf"
    "pBEF7wM4h8Tq5n+B6h4/otUWoJGIF5CBFkHk5ndc9BKGVq9BnJAHkBzKaSEGYRQ3cZyWKrEp"
    "9Xbh1Y1CJHFIP1j5WgCYs84DvOJX4Jofqu6rtXAYpj44dYTzpo60vw+0AOYh3bJv/1d3XnwR"
    "09ojn5mjf6DDwkN7mzntDRE/6sl76voPFJeuZ3hZg6w9RKM9QiqerOSS2ROzDx3T80jyNtGV"
    "ZKkSVElFcQpOq23JVUFLV008RoeMNgkgP330GJ9bdR69mFebk+QQZuZolyU5/dUFzbmCfgTN"
    "A5oImQhBlVhaIVsAmLOLtwChOl/Wvg82rwNdDvIm4HyIJ8ENLwxw4I6HVqxmcCSBtiLrI6tG"
    "SzQPJFlJ6lwMlyYP9jt9Fg6Xo/0vz7/4fCZCg1QZ/Pmtl9GOw2zLh2j4nNIXVdUMPUgUQQmu"
    "qvyiDherS5DLWF23+JdrLmAqwsroKClIyVE9wcXlAjP0JmZoHUrp+ib5sa00Rh4FRmkMnoBy"
    "zMrYAsCc3elN5MXAr4GsBL0S3AXg7wRdGwZf41gxUkLZpYgBiUroV7ftLnpU1dc7kraQbkmm"
    "JUv3zH5x/sWXsAoa15cJDx91hNlZ5lcN0cyGScp5CG1UfXXNnoI4wXmHlg7tK4NumC4wpMoR"
    "MiQtSI8GykM5zU6fJ3rHLx7H75+kHydQKUGn6c2swbmc7vQFpKnNAVgAmG8xCPhD0NdR1T+A"
    "n6hCQahPAv44aI8iekL3MZSI1NtxeydEBeeru/hQlizgaaU5slGfODgdR0ceOIDIjX/7ANOM"
    "rT557faDI+1B0qJPKYMELUlLIYRqzxCh3n/QCWUjZb6sRvRbjuxjfvky6CbEfBbpHWSoFzbm"
    "DE7Ok7R2UXQ24ZKjUIzjW0fQEKreSxy1MrYAMGeh+sn3A+9/3pi48vtfQpFtR7yrbtUtQojg"
    "pdqjv9RA5+BlpMku8s4q/OQ8rBh+cg9o/JvrZf1Ft5H5Czq9g0k+SE8yUgIEIQkFTRw4IbqE"
    "MnE4r1UinJwjUf30ta+4TX6m1+XiAElvHtfpZAVjV+9msNElnx9gaOghEEHjYVSqfgSqSDhp"
    "pfzCswWZ/9zlLU+aehIVHNVGOyKKeIePSj4zQd4NLHRXMz+bMbN/ks6MO35oYnTyEtrEZepm"
    "vzn4zXtHmjv3MZ4O4EOkCNCPKXmuZIWSFQ6ngibVTcBcrC/nSXJcklK0ctrzOSkrlh2DkZyy"
    "C7Hv0DISi4iqQBDKXClLxWfW+FgPwHzb2qmjCJEEiN6RhuoOvWVUFGiOnCQbOY7DkWwUYqyL"
    "fXV2dHq4ZPmjUzFs30e+Lhvc+NEVxzrkE+M0Zo8TkwwGWnTLEikcgwswL0CS4gerG4Kzs0fx"
    "9BNcMyE8MltygtmBjfQeXI6LcygpWmxCXE7iGwSOELTJ2vOfxHtrfCwAzD+YCLj6InvB47Wg"
    "EIfXiMMt3bDTOaotwxs5yZDS3BvxMyVhXu/9+i2H10x8yr1oA5O5gywjcSlJmlEGQUNgmEjM"
    "BaJUk5QHjlImw3xFhIHyxPpJmlsOkJYdGs0FuvMTNNoHKHsJaROKIifQJskSgu0JaAFgvn1l"
    "UDSpuv9aKlEEISDekQQQV3XWY4Qo1S27UCUCa+eE2esjhYu0mkqrLJ8++j0Dl2/7XIwpWmaA"
    "pxQlBugDiXqko/QP15t6z8y1R5e1OkXeYp6BjQ63+hBuviTxQjZ0oFq0PKw4FVoRut2MUAZC"
    "3/YEtAAw/yC8VhU/EUXFEUKoF/MG1Llq798zewt9oAHaCKQxpz8nZG1PFoq5BRbU01wo6aeO"
    "RizRWFIkQgiK9kvinsM+qT9BZb7ARK6cxLUKwskSvJL76sZFsb57kddIWXgk6dKZSUmSphXc"
    "C8/GYf/ciU+qKqZKXrfsaeLJi0geFY0KWq3uT6jXBIggA449AJLigLQBvojo6nj3VzkIqEby"
    "oiD4JknaJj18nMbOgzQfPcwApVYteF66Wdbr7NwFY+TaJWkLvlSSPrgAWRBcCRoEF8GlfWgW"
    "uMTuDXgufHzscmBjbAhgXqgE3v6jryXW621CVDygUvXMvK/30FPBaSQmbunv4j3Z7GfotjeC"
    "biZQLdL19WSfOiHGauydNhxFv1rFK4WiqRCDp1d+nHZ2ORrXE8sIfSFNhbwFg0lKbHq6s+Af"
    "ENJ2i+LCLvO7l9P7xjjFQKH7p94ra172SuKxK0ibHSQEyCNlEvBpE5dMI5oSikFikjK4fCfN"
    "diTzUC6I3v+xP7dPgAXAd3gCyAYSF6qL+xc3zqz+ARchOI/EQPD1LH615g+iEhspnjGCnIdf"
    "PAOgUm+6GRFfTw6qx0mB4lFX1n+PTLYdnf4E4jbgfKTbVvI8EhequQS6guDoX+Pp9yFJRhnZ"
    "6GiNzVFo9X7LJxN0ZBYXU6RZ0NcE7TmyLOJiG/UOLwVloUiyllIj3RKS1HYItDkAQ4iBMlZj"
    "+NMn61SrZb1OFK8KKkiIqPPVQh/nmaG6YiBfHOd7R1lPujlAoyeUgaKIhBAp6zmCEAORapuu"
    "0gkuBhClASSZo9nwuExwXvAu4suA26FwDPIyJ6ePa1V3HpKHm7hmghssUe/Ikkg2JCRJRJoO"
    "l4Im1Y3FXQpJPQeRpPbZswAwVcWnnpn31VX3isOLVktoF8+Xy5kz+dXj6oWk7vZH1aUSDVrd"
    "gUe9I7pIAEQXf+rU+1JWN+kI9U+6+lgWX69cDJONig44srxFOpTQGKh6jy0SpPTE+vUWN/3U"
    "Mxb6LL6ug2pNgk0+2RDAsFS5fVTULVaUartPXdw+y7ul/fTrAUA1uw9IqOYNEIF6FaCGSJI5"
    "Yqk4HBpKpF6Df2b0+wREPK4oiKlHwqnbdi1WWg0RUoc70SDZN45r9dGJakOP0E9JXEosC9RV"
    "FyEICrG6IEnquwEXItXpSmt2rAdgnqMj4OSMFr5u9VURPGhVmWVxqW8ZmF/QxYkEpJ44lKgI"
    "1dp70bjUMv//vH8sT70ep/UEAJRI0gTXS2nuHnLl5+qeRieFZhufKkVvDFRJfbU4ScpT5/oX"
    "l/1I3TOIdmsg6wGYU5V98Ry9REVUqnG+CtE7ICB1hVHvoFSyxDM4INU1ACoUsdqsS7XayS+W"
    "Zd1DiEu34SpjvRQ4ntptIEYlxmrlXkSXhgcxKmmEov65BEdYUcKmkvLhZmy3qrsXHsmX4R/f"
    "zELu8ckwSbqW0HfgZ8kGAsMr9+G94L1Dy1Adn8jSJKKxAPiOr/xOqktrRKv754HgVIhEnNRn"
    "AaTq/jscIoFQ9xhKQOqd+pCq1S+pNvPyzqMuouKryifVqcFnDPRrpSpJ/Xp1X4LoFOeERIQy"
    "KNLtE+lVm/p1qzZ9YOhpGG8gvT4SPEljjq4mNEaO4RnCoaj3S8MTiZHgBIk2B2ABYKoLeFSX"
    "Kq/iEFHUeQjlM0JCQwDvqsm5IIwA84CP1VX6i/VaqE4DlqKkCipCqDfijfULOvfswWB52vE4"
    "ByEKoVuSd0sagxmtZoKs6RM6reiyDICxKyM60iEWBV4WCCosWwV9dYQwh6M6e1FtK1jvKrj4"
    "3VgA2OC/nsxzgg+R6D0aQ11hpJ4QFJRqo16pw8JrZKYeWy9OrEWtFw1JrNYR1I8RQ3UFYL3V"
    "ZzxtgB/qO/XGqEubdUQgEyEncmJ/xsn9k7jBg4w2FmDS4TrzNJgA4MRsn/LQNAsnBZyQNIdY"
    "saFLMpwt3Q9QA9XE4JlzHMYCwHoAsjQWL4AYyuqxGKrts6Oiruo6i/NoLBGf4ELJSN1qq5NT"
    "FcpV3fdSFReqPQGIEBdvJFb3FBYnBrxfHItLNXGILh1TPS7BZweY27fGzccFeCKN0CHJqm1B"
    "d989jMoAZV8zF4dy1xqmtWwng82kWr/gQLwn1NcleKqrDLwNASwATLXs12vVRT41/mZpAs+J"
    "sLiDfgxVL0BDxCWemRIyLyTxVGsf9bQKLKfOty+27kuPPcfZAa2nAV3dC0gSYWxlYHi5Z371"
    "dER7hJiSuB5J1gVg3RXH8JngEpd35xfQsMDAUFb1VNypHkh1NqL6P1ZDDJsEtAAwINWMexSp"
    "duGvK6g4X42TnZCEsLQWQPCoBLS+Gi+TxVt2LLbj1fh68XvV0iun98Djs1OoGh7U7720EChC"
    "NuRw0qQ1Ak4a1XN1gHpXUMY3CpEWkniGQiRqSSI+lsRcAAACVUlEQVRJdWWiUi1ZRqvFSvWm"
    "pebc6YDar+AF5pemAk6t5luql05QHEEEwqnnoIpqZISqa+9VkbpFFXl2BYunfXHaasGl90lk"
    "qTdSzUf4pVt4x1LpdcPScZVn9FSK+v3KfqQMSozVc2LUZ4TN4t+dfeosAMwpeYj1Lj7xVKWL"
    "IDFAqL6ruCooEkFjqJ5fTwJKUPqLwwXqHfxF8PXGoAlUa+/PCIPFkj99PUC1dK96bep1AS4R"
    "sqbDufosQV2DZXHpcD2n4LzgXPVdYtXFj4vLmIMAz2z97ZN3jvQ/rUdmjPUAjDEWAMYYCwBj"
    "jAWAMcYCwBhjAWCMsQAwxlgAGGMsAIwxFgDGGAsAY4wFgDHGAsAYYwFgjLEAMMZYABhjLACM"
    "MRYAxhgLAGOMBYAxxgLAGGMBYIyxADDGWAAYYywAjDEWAMYYCwBjjAWAMcYCwBhjAWCMsQAw"
    "xlgAGGMsAIwxFgDGGAsAY4wFgDEWAMYYCwBjjAWAMcYCwBhjAWCMsQAwxlgAGGMsAIwxFgDG"
    "GAsAY4wFgDHGAsAYYwFgjLEAMMZYABhjLACMMRYAxhgLAGOMBYAxxgLAGGMBYIyxADDGWAAY"
    "YywAjDEWAMYYCwBjjAWAMcYCwBhjAWCMsQAwxlgAGGMsAIwxFgDGGAsAY4wFgDHGAsAYYwFg"
    "jAWAMcYCwBhjAWCMsQAwxlgAGGMsAIwxFgDGGAsAY4wFgDHGAsAYYwFgjLEAMMZYABhjLACM"
    "MRYAxhgLAGOMBYAxxgLAGGMBYIyxADDGWAAYYywAjDEWAMaYf1T/DwxH3l4E1hKeAAAAAElF"
    "TkSuQmCC").GetImage()

def getErrorImage():
    """Generate 'pending' image from embedded data.

    This file was generated by /usr/local/bin/img2py
    We used to have a separate image file for this, but this is better.
    """

    return PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAAAXNSR0IArs4c6QAAAAlwSFlz"
    "AAALEwAACxMBAJqcGAAAAAd0SU1FB9wDCQACMfBoIRYAAAAZdEVYdENvbW1lbnQAQ3JlYXRl"
    "ZCB3aXRoIEdJTVBXgQ4XAAAMd0lEQVR42u3b23Pb5oGG8RcnAiQIgpRdUbJ8jONNk4tM053O"
    "XvZv701vsrvqtJMeMtvYUZSKlHWgxBNAEOBeGGKhCKQkS4oZ6/ldaUSK/AYiHnz4ABrHf/3r"
    "rBfHAnC/NF1Xdi+O9f3JCVsDuG/CUCZbAbi/CABAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAA"
    "EAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAA"
    "ABAAAAQAAAEAQAAAEAAABAAAAQAIAJsAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIA"
    "gAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAAC"
    "AIAAACAAAAgAAAIAgAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQCw"
    "2mw2wWr4/dOn85//sLNz7ccBAvABd9r3xc4MAgDcwawJBOBOLfvQXffDyQcYHwKLgAABAMAp"
    "AH7x57OmYehxEKheqch3HLmWpWGSaDCZqDMcqj+Z3Po412s1rVWranmestlMg8lEPw4G6kXR"
    "pa9XtW1tBYFqjiPfcSRJwyTRMEn0Y7+vaDpdOoZlv+O0igDcK03P02dra/Ls8//Whuuq4bra"
    "qNf1utfTbr9/a+/52dqaNur1c7/zbFsPqlV9d8l7bdXretFsyjLPT0QrlqWW52nT9/Vdr6d/"
    "DQb8cwkAlml5nr5cX5ckzWYzvTk50cF4rHg6VcN19arVUtVx9LLVkqRbicAnzaZanqdv3r7V"
    "SRzLNAxt1Ot6HoYyDEOfNJt6OxopTtOLO38Q6NN8LNMs0/8dH+s4imTkIfu01ZJtmnq1tiZJ"
    "5yJwdmTnKgBrAJBkSHqV70yS9M3BgXZOTzVKEqWzmY6jSNvdrqZZJkl6HoaqWNaN33fD9/U/"
    "nY4OxmMlWaY4TfX9yYk6+c5qGIaeNBoX/s4xTT0PQ0lSNptpu9tVdzjUJE0Vp6m6w6H+1O0q"
    "m83ejbfZlG3yUSUAKJ9KB4Gq+flzP451OB5feE6SZdofDiVJlmnqacmOeV0/9PtK8qgUdfL3"
    "kaR6pXLh8cdBMN+hO8OhRkly4TnDJFE3fx3HNPU4CPhHEwCUabju/Oed09OFz9srTKPLdszr"
    "OioJjSSNCzu0VzLT8AvvvV+IxU91LwkJWAOA3q2kn/ni4cPFpwqG8e+dMJ8x3ETZCr0kTQqz"
    "grJTjVphvIte46ePVW0+qgQAlwaguJMv/cffwjl1mp+jL12fKBlPMQqTkgXCssfcW1izAAH4"
    "KMVpqlq+Q/9xd7f0vHxVx1uxrNKrBD8NRbwkFGAN4F4rLqLdxtT+ro0LU3tvydS++Nh4yakC"
    "CMC9Vry7L/S8lR/vsDDe9Vpt4fPavj//eVByB2NamOkYfAwIwH31Y7+vOD9CPgmCpUfVVbDb"
    "78/vSWj7fukCX81x5gFIsqz0xqXiIqHLIiEBuK/S2UzfHh1JeneN/7fttp42GvIdR5ZhyDQM"
    "VW1bTc/TJ82mfre5+UHHm2SZ3pyczMf71caG1ms1VSxLFctS2/f1VbstM19AfNPrzYNRNCic"
    "+jxrNFgofA9k8yNxFEX6y/6+XuXfBXjRbOpFs7nSsxZJehGGckxTn5dcvkyzbOl3AV73enpY"
    "rcoyTW3U6xe+k8DtwQTg3kXg6709bdXrClxXNdtW1XGUZpkmaarxdKrjKNLRFb6l93NF4Gg8"
    "1lYQyHcc1fIFzFH+bcDdBd8GPBOnqb7e29PjRkOh68q1LDmmeeVLoZCM19vbs+/z6RiA++NZ"
    "GLIGANxnBAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAA"
    "AAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAK7LZhN8/H7/9On85z/s7Fz78Z9j"
    "DD/364AZAEAA2AQApwD4iDFVBjMAAAQAAKcAl/JsWy3PU8vzVLVtuZYl0zAUp6mi6VQncazd"
    "fl/ZbHbhb/9zY0P1SkWS9O3RkfYGg4Xvs1mv6z/W1iRJ/clE/9vp3No4ztx05fw2xnDhyGMY"
    "Wq/V1PI8NT1PaZapP5lofzTS4Xh88yObYehxEKheqch3HLmWpWGSaDCZqDMcqj+Z8CEnAIv9"
    "16NHpb+vmaZqjqO1alVbQaB/HB7qKIrOPWdvMNCrfKfe9P1LA3CmU/K8m4xjFbbFIr9+8EC/"
    "qtX+/QvLUtVxtO77+uH0VN/1eu893qbn6bO1NXn2+Y93w3XVcF1t1Ot63etpt98nAOzq5YZJ"
    "ooPRSMdRpDhNNUlTebat0HUVuq7WazVVLEu/fvBAX+/tKcmy+d/uj0Z62WrJNAwFrivfcTRM"
    "kgvv4TuOgnymkM1m2h+NbnUcq7AtyrxsNtX0PP398FDHeTBanqdPWy3ZpqknjYay2UxvTk6u"
    "PdaW5+nL9XVJ0ix/jYPxWPF0qobr6lWrparj6GWrJUn3PgKsASzw33t7enNyopM4VjSdKpvN"
    "NEoS7Q0G+vvhof6ZH6Ecy9KzMDz3t9Ms00FhZ97w/dL32Cgc/Q9GI01LdpybjGMVtsWiWc92"
    "p6PucKhJHpTucKjtbnd+GvE4COSY1/t4GpJe5Tu2JH1zcKCd01ONkkTpbKbjKNJ2tzvfzs/D"
    "UBXLIgC4vu5wOP/57Hz/3GlA4fG278so+bC2C1PgZacJNxnHKmyLsuePp9MLvx8liTr5a1mm"
    "qceNxrXGsRUEqjrOu/WUOC5dS0iyTPuF93h6zffgFOA+bRzT1Fa9rtDz5FqWXMuSVXJUqtkX"
    "N2MvihRNp/JsW45l6WGtpreFWcHDWk1OfvSJplP14vhOxrEK2+JCAEpOdeanT8OhHuUzo3q+"
    "M19Vw3XnP++cni583t5goEdB8EGjSQBW3Ga9rpfNZumH/KecBdPIzmCg583m/DTg7YLTgs4l"
    "i4Q3HccqbIuiuOTofyYqPFa9ZtCKz//i4cPFpwqGcW4dhgDgnDBfLDIMQ9lspt1+XwejkeI0"
    "VZKmOrvYVby8VhqA4VDPwlCGYaiVHznjNJVrWWp53nyhqlOYQt/FOFZhWxRN0vRKj133/LwY"
    "gOJOftnMhgDgwrnk2Qfon8fH+lfJEdq9ypEuTXUcRVqrVmUYhtq+r53TU234/vz1z1bW73Ic"
    "q7Atiip5CBc9dpVQLNretXyH/uPu7p1cEfnYsAhYIiicFx4suCnlqtPT4tH9bNW/Xbz2v+Do"
    "f9vjWIVtMQ/GkucXr92Pl5wqlBkVLrXe96k9AbjJtKgwLbQWTCWLl/CWORiNlORHsqpt63kY"
    "zneYJE3PXS68y3GswrY4s168AWjJY4OSeyeWKd7dF+anWCAA11Y8krRLruE3KpWlH+Kimc6v"
    "ehcvO3VHI81+pnGswraYB8P3S2cNNduexyTNMu0uWckv82O/P19gfBIEF+4EBAG4kuIdeVtB"
    "MD9qe5alzXpdX66vX+sOsuIqf3FxqnPJtf/bHscqbAvp3T0SX7Xb8zsIK5al9VpNv9nYkJlv"
    "n91+/9rn8Olspm+Pjt7NVkxTv2239bTRkO84sgxDpmGoattqep4+aTb1u81NZrvs7uVHkgfV"
    "qlqeJ9s09SwMz93h1hkM9F2vpydXvIlkmCTqTybnzqf7cVx6e/BdjmMVtoX0bjHRsyx9vuBS"
    "3Q+np+91G7AkHUWR/rK/r1f5dwFeNJt6kV+KBQG4sj/v7+tRva5131fNcTRNU53EsXpxfO7O"
    "tysf9QYDBfkXhM6Ogh9iHKuwLSTpb4eHakeRWp6n0HVv9duAR1Gkr/f2tFWvK3Bd1WxbVcdR"
    "mmWapKnG06mOo+jOvjz1S2K83t6eff+etQXwy/UsDFkDAO4zAgAQAAAEAAABAEAAABAAAAQA"
    "AAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAE"
    "AAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAACwCYACAAAAgCAAAAgAAAIAAACAIAAACAA"
    "AAgAAAIAgAAAIAAACAAAAgCAAAAgAAAIAAACAIAAACAAAAgAAAIAgAAAIAAACAAAAgCAAAAg"
    "AAAIAAACAIAAACAAAAgAAAIAgAAAIAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAA"
    "BAAAAQBAAACsNrvpulIYsiWAe6bpuvp/KMHzybJ4Z08AAAAASUVORK5CYII=").GetImage()

######
# Override the pyCacheBack object to handle OSM tile retrieval
######

class OSMCache(pycacheback.pyCacheBack):

    def _get_from_back(self, key):
        """Retrieve value for 'key' from backing storage.

        key  tuple (level, x, y)
             where level is the level of the tile
                   x, y  is the tile coordinates (integer)

        Raises KeyError if tile not found.
        """

        # look for item in disk cache
        tile_path = os.path.join(self._tiles_dir, TilePath % key)
        if not os.path.exists(tile_path):
            # tile not there, raise KeyError
            raise KeyError

        # we have the tile file - read into memory, cache it & return
        image = wx.Image(tile_path, wx.BITMAP_TYPE_ANY)
        bitmap = image.ConvertToBitmap()
        return bitmap

    def _put_to_back(self, key, value):
        """Put a bitmap into on-disk cache.

        value  the wx.Image to save
        key     a tuple: (level, x, y)
                where level  level for bitmap
                      x      integer tile coordinate
                      y      integer tile coordinate
        """

        tile_path = os.path.join(self._tiles_dir, TilePath % key)
        dir_path = os.path.dirname(tile_path)
        try:
            os.makedirs(dir_path)
        except OSError:
            # we assume it's a "directory exists' error, which we ignore
            pass
        value.SaveFile(tile_path, wx.BITMAP_TYPE_JPEG)

################################################################################
# Worker class for internet tile retrieval
################################################################################

class TileWorker(threading.Thread):
    """Thread class that gets request from queue, loads tile, calls callback."""

    def __init__(self, server, tilepath, requests, callafter, error_tile):
        """Prepare the tile worker.

        server     server URL
        tilepath   path to tile on server
        requests   the request queue
        callafter  function to CALL AFTER tile available

        Results are returned in the CallAfter() params.
        """

        threading.Thread.__init__(self)

        self.server = server
        self.tilepath = tilepath
        self.requests = requests
        self.callafter = callafter
        self.error_tile_image = error_tile
        self.daemon = True

    def run(self):
        while True:
            (level, x, y) = self.requests.get()

            try:
                tile_url = self.server + self.tilepath % (level, x, y)
                f = urllib2.urlopen(urllib2.Request(tile_url))
                if f.info().getheader('Content-Type') == 'image/jpeg':
                    image = wx.ImageFromStream(f, wx.BITMAP_TYPE_JPEG)
                else:
                    # tile not available!
                    image = self.error_tile_image
                wx.CallAfter(self.callafter, level, x, y, image)
            except urllib2.HTTPError, e:
                log('ERROR getting tile %d,%d,%d from %s\n%s'
                    % (level, x, y, tile_url, str(e)))

            self.requests.task_done()

################################################################################
# Class for OSM tiles.   Builds on tiles.Tiles.
################################################################################

# where earlier-cached tiles will be
# this can be overridden in the OSMTiles() constructor
DefaultTilesDir = 'osm_tiles'

# set maximum number of in-memory tiles for each level
DefaultMaxLRU = 10000

class OSMTiles(tiles.Tiles):
    """An object to source OSM tiles for pySlip."""

    TileSize = 256      # width/height of tiles

    # the pool of tile servers used and tile path on server
    # to each tile, %params are (level, x, y)
# OSM tiles
    TileServers = ['http://otile1.mqcdn.com',
                   'http://otile2.mqcdn.com',
                   'http://otile3.mqcdn.com',
                   'http://otile4.mqcdn.com']
    TileURLPath = '/tiles/1.0.0/osm/%d/%d/%d.jpg'
    TileLevels = range(17)
# satellite tiles
#    TileServers = ['http://oatile1.mqcdn.com',
#                   'http://oatile2.mqcdn.com',
#                   'http://oatile3.mqcdn.com',
#                   'http://oatile4.mqcdn.com']
#    TileURLPath = '/tiles/1.0.0/sat/%d/%d/%d.jpg'
#    TileLevels = range(13)         # [0, ..., 12] for the satellite tiles

    # maximum pending requests for each tile server
    MaxServerRequests = 2

    def __init__(self, tiles_dir=None, tile_levels=None, callback=None,
                 http_proxy=None, pending_file=None, error_file=None):
        """Override the base class for local tiles.

        tiles_dir     tile cache directory, may contain tiles
        tile_levels   list of tile levels to be served
        callback      caller function to call on tile available
        http_proxy    HTTP proxy to use if there is a firewall
        pending_file  path to picture file for the 'pending' tile
        error_file    path to picture file for the 'error' tile
        """

        # check tiles_dir & tile_levels
        if tiles_dir is None:
            tiles_dir = DefaultTilesDir
        self.tiles_dir = tiles_dir

        if tile_levels is None:
            tile_levels = self.TileLevels
        self.levels = tile_levels
        self.level = None

        # set min and max tile levels
        self.min_level = min(self.levels)
        self.max_level = max(self.levels)

        # save the CallAfter() function
        self.callback = callback

        # tiles extent for OSM tile data (left, right, top, bottom)
        self.extent = (-180.0, 180.0, -85.0511, 85.0511)

        # prepare tile cache if not already there
        if not os.path.isdir(tiles_dir):
            if os.path.isfile(tiles_dir):
                msg = ("%s doesn't appear to be a tile cache directory"
                       % tiles_dir)
                raise Exception(msg)
            os.makedirs(tiles_dir)
        for level in self.TileLevels:
            level_dir = os.path.join(tiles_dir, '%d' % level)
            if not os.path.isdir(level_dir):
                os.makedirs(level_dir)

        # setup the tile cache (note, no callback set since net unused)
        self.cache = OSMCache(tiles_dir=self.tiles_dir, max_lru=DefaultMaxLRU)

        # set the list of queued unsatisfied requests to 'empty'
        self.queued_requests = {}

        # OSM tiles always (256, 256)
        self.tile_size_x = self.TileSize
        self.tile_size_y = self.TileSize

        # prepare the "pending" and "error" images
        if pending_file:
            self.pending_tile_image = wx.Image(pending_file, wx.BITMAP_TYPE_ANY)
        else:
            self.pending_tile_image = getPendingImage()
        self.pending_tile = self.pending_tile_image.ConvertToBitmap()

        if error_file:
            self.error_tile_image = wx.Image(error_file, wx.BITMAP_TYPE_ANY)
        else:
            self.error_tile_image = getErrorImage()
        self.error_tile = self.error_tile_image.ConvertToBitmap()

        # test for firewall - use proxy (if supplied)
        test_url = self.TileServers[0] + self.TileURLPath % (0, 0, 0)
        try:
            urllib2.urlopen(test_url)
        except:
            log('Error doing simple connection to: %s' % test_url)
            log(''.join(traceback.format_exc()))

            if http_proxy:
                proxy = urllib2.ProxyHandler({'http': http_proxy})
                opener = urllib2.build_opener(proxy)
                urllib2.install_opener(opener)
                try:
                    urllib2.urlopen(test_url)
                except:
                    msg = ("Using HTTP proxy %s, "
                           "but still can't get through a firewall!")
                    raise Exception(msg)
            else:
                msg = ("There is a firewall but you didn't "
                       "give me an HTTP proxy to get through it?")
                raise Exception(msg)

        # set up the request queue and worker threads
        self.request_queue = Queue.Queue()  # entries are (level, x, y)
        self.workers = []
        for server in self.TileServers:
            for num_threads in range(self.MaxServerRequests):
                worker = TileWorker(server, self.TileURLPath,
                                    self.request_queue, self._tile_available,
                                    self.error_tile_image)
                self.workers.append(worker)
                worker.start()

    def UseLevel(self, level):
        """Prepare to serve tiles from the required level.

        level  the required level
        """

        if level not in self.levels:
            return None
        self.level = level

        # get tile info
        info = self.GetInfo(level)
        if info is None:            # level doesn't exist
            return None
        (self.num_tiles_x, self.num_tiles_y, self.ppd_x, self.ppd_y) = info

#        # store partial path to level dir (small speedup)
#        self.tile_level_dir = os.path.join(self.tiles_dir, '%d' % level)

        # finally, return True
        return True

    def GetInfo(self, level):
        """Get tile info for a particular level.

        level  the level to get tile info for

        Returns (num_tiles_x, num_tiles_y, ppd_x, ppd_y).

        Note that ppd_? may be meaningless for some tiles, so its
        value will be None.
        """

        self.num_tiles_x = int(math.pow(2, self.level))
        self.num_tiles_y = int(math.pow(2, self.level))

        return (self.num_tiles_x, self.num_tiles_y, None, None)

    def GetTile(self, x, y):
        """Get bitmap for tile at tile coords (x, y) and current level.

        x  X coord of tile required (tile coordinates)
        y  Y coord of tile required (tile coordinates)

        Returns bitmap object for the tile image.
        Tile coordinates are measured from map top-left.

        We override the existing GetTile() method to add code to retrieve
        tiles from the internet if not in on-disk cache.
        """

        try:
            tile = self.cache[(self.level, x, y)]
        except KeyError:
            # start process of getting tile from 'net, return 'pending' image
            self.GetInternetTile(self.level, x, y)
            tile = self.pending_tile

        return tile

    def GetInternetTile(self, level, x, y):
        """Start the process to get internet tile.

        level, x, y  identify the required tile

        If we don't already have this tile (or getting it), queue a request and
        also put the request into a 'queued request' dictionary.  We
        do this since we can't peek into a Queue to see what's there.
        """

        tile_key = (level, x, y)
        if tile_key not in self.queued_requests:
            # add tile request to the server request queue
            self.request_queue.put(tile_key)
            self.queued_requests[tile_key] = True

    def _tile_available(self, level, x, y, image):
        """A tile is available.

        level  level for the tile
        x      x coordinate of tile
        y      y coordinate of tile
        image  tile image data
        """

        # convert image to bitmap, save in cache
        bitmap = image.ConvertToBitmap()

#        image.SaveFile('osm_%d_%d_%d.jpg' % (level, x, y), wx.BITMAP_TYPE_JPEG)
        
        self._cache_tile(image, bitmap, level, x, y)

        # remove the request from the queued requests
        # note that it may not be there - a level change can flush the dict
        try:
            del self.queued_requests[(level, x, y)]
        except KeyError:
            pass

        # tell the world a new tile is available
        wx.CallAfter(self.available_callback, level, x, y, image, bitmap)

    def _cache_tile(self, image, bitmap, level, x, y):
        """Save a tile update from the internet.

        image   wxPython image
        bitmap  bitmap of the image
        level   zoom level
        x       tile X coordinate
        y       tile Y coordinate

        We may already have a tile at (level, x, y).  Update in-memory cache
        and on-disk cache with this new one.
        """

        self.cache[(level, x, y)] = bitmap
        self.cache._put_to_back((level, x, y), image)

    def Geo2Tile(self, xgeo, ygeo):
        """Convert geo to tile fractional coordinates for level in use.

        xgeo   geo longitude in degrees
        ygeo   geo latitude in degrees

        Note that we assume the point *is* on the map!

        Code taken from [http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames]
        """

        lat_rad = math.radians(ygeo)
        n = 2.0 ** self.level
        xtile = (xgeo + 180.0) / 360.0 * n
        ytile = ((1.0 - math.log(math.tan(lat_rad) + (1.0/math.cos(lat_rad))) / math.pi) / 2.0) * n

        return (xtile, ytile)

    def Tile2Geo(self, xtile, ytile):
        """Convert tile fractional coordinates to geo for level in use.

        xtile  tile fractional X coordinate
        ytile  tile fractional Y coordinate

        Note that we assume the point *is* on the map!

        Code taken from [http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames]
        """

        n = 2.0 ** self.level
        xgeo = xtile / n * 360.0 - 180.0
        yrad = math.atan(math.sinh(math.pi * (1 - 2 * ytile / n)))
        ygeo = math.degrees(yrad)

        return (xgeo, ygeo)


if __name__ == '__main__':
    import unittest

    DefaultAppSize = (512, 512)
    DemoName = 'OSM Tiles Test'
    DemoVersion = '0.1'


    # we need a WX app running for the test code to work
    class AppFrame(wx.Frame):

        def __init__(self):
            wx.Frame.__init__(self, None, size=DefaultAppSize,
                              title='%s %s' % (DemoName, DemoVersion))
            self.SetMinSize(DefaultAppSize)
            self.panel = wx.Panel(self, wx.ID_ANY)
            self.panel.SetBackgroundColour(wx.WHITE)
            self.panel.ClearBackground()
            self.Bind(wx.EVT_CLOSE, self.onClose)

            unittest.main()

        def onClose(self, event):
            import time
            time.sleep(10)
            self.Destroy()


    class TestOSMTiles(unittest.TestCase):

        def test_Tile2Geo(self):
            """Exercise tiles.Tile2Geo() at various known places."""

            tiles = OSMTiles(tiles_dir=DefaultTilesDir)
            tiles.UseLevel(2)
            (min_lon, max_lon, min_lat, max_lat) = tiles.extent

            # check lon/lat of top left corner of map
            expect_lon = min_lon
            expect_lat = max_lat
            tile_x = 0.0
            tile_y = 0.0
            (lon, lat) = tiles.Tile2Geo(tile_x, tile_y)
            msg = 'Expected geo (%f,%f) but got (%f,%f)' % (expect_lon, expect_lat, lon, lat)
            self.assertAlmostEqual(expect_lon, lon, places=3, msg=msg)
            self.assertAlmostEqual(expect_lat, lat, places=3, msg=msg)

            # check lon/lat of bottom left corner of map
            expect_lon = min_lon
            expect_lat = min_lat
            tile_x = 0.0
            tile_y = tiles.num_tiles_y
            (lon, lat) = tiles.Tile2Geo(tile_x, tile_y)
            msg = 'Expected geo (%f,%f) but got (%f,%f)' % (expect_lon, expect_lat, lon, lat)
            self.assertAlmostEqual(expect_lon, lon, places=3, msg=msg)
            self.assertAlmostEqual(expect_lat, lat, places=3, msg=msg)

            # check lon/lat of top right corner of map
            expect_lon = max_lon
            expect_lat = max_lat
            tile_x = tiles.num_tiles_x
            tile_y = 0.0
            (lon, lat) = tiles.Tile2Geo(tile_x, tile_y)
            msg = 'Expected geo (%f,%f) but got (%f,%f)' % (expect_lon, expect_lat, lon, lat)
            self.assertAlmostEqual(expect_lon, lon, places=3, msg=msg)
            self.assertAlmostEqual(expect_lat, lat, places=3, msg=msg)

            # check lon/lat of bottom right corner of map
            expect_lon = max_lon
            expect_lat = min_lat
            tile_x = tiles.num_tiles_x
            tile_y = tiles.num_tiles_y
            (lon, lat) = tiles.Tile2Geo(tile_x, tile_y)
            msg = 'Expected geo (%f,%f) but got (%f,%f)' % (expect_lon, expect_lat, lon, lat)
            self.assertAlmostEqual(expect_lon, lon, places=3, msg=msg)
            self.assertAlmostEqual(expect_lat, lat, places=3, msg=msg)

            # check lon/lat of middle of map
            expect_lon = min_lon + (max_lon - min_lon)/2.0
            expect_lat = 0.0
            tile_x = tiles.num_tiles_x / 2.0
            tile_y = tiles.num_tiles_y / 2.0
            (lon, lat) = tiles.Tile2Geo(tile_x, tile_y)
            msg = 'Expected geo (%f,%f) but got (%f,%f)' % (expect_lon, expect_lat, lon, lat)
            self.assertAlmostEqual(expect_lon, lon, places=3, msg=msg)
            self.assertAlmostEqual(expect_lat, lat, places=3, msg=msg)

        def test_Geo2Tile(self):
            """Exercise Geo2Tile() at various known places."""

            tiles = OSMTiles(tiles_dir=DefaultTilesDir)
            tiles.UseLevel(2)
            (min_lon, max_lon, min_lat, max_lat) = tiles.extent

            # calculate where (0,0)(Tile) should be in geo coords, check
            expect_xtile = 0.0
            expect_ytile = 0.0
            geo_x = min_lon
            geo_y = max_lat
            (xtile, ytile) = tiles.Geo2Tile(geo_x, geo_y)
            msg = ('Expected tile (%f,%f) but got (%f,%f)'
                   % (expect_xtile, expect_ytile, xtile, ytile))
            self.assertAlmostEqual(expect_xtile, xtile, places=3, msg=msg)
            self.assertAlmostEqual(expect_ytile, ytile, places=3, msg=msg)

            # calculate where (.num_tiles_x,0)(Tile) should be in geo coords, check
            expect_xtile = tiles.num_tiles_x
            expect_ytile = 0.0
            geo_x = max_lon
            geo_y = max_lat
            (xtile, ytile) = tiles.Geo2Tile(geo_x, geo_y)
            msg = ('Expected tile (%f,%f) but got (%f,%f)'
                   % (expect_xtile, expect_ytile, xtile, ytile))
            self.assertAlmostEqual(expect_xtile, xtile, places=3, msg=msg)
            self.assertAlmostEqual(expect_ytile, ytile, places=3, msg=msg)

            # calculate where (0,.num_tiles_x)(Tile) should be in geo coords, check
            expect_xtile = 0.0
            expect_ytile = tiles.num_tiles_y
            geo_x = min_lon
            geo_y = min_lat
            (xtile, ytile) = tiles.Geo2Tile(geo_x, geo_y)
            msg = ('Expected tile (%f,%f) but got (%f,%f)'
                   % (expect_xtile, expect_ytile, xtile, ytile))
            self.assertAlmostEqual(expect_xtile, xtile, places=3, msg=msg)
            self.assertAlmostEqual(expect_ytile, ytile, places=3, msg=msg)

            # calculate where (.num_tiles_x,.num_tiles_x)(Tile) should be in geo coords, check
            expect_xtile = tiles.num_tiles_x
            expect_ytile = tiles.num_tiles_y
            geo_x = max_lon
            geo_y = min_lat
            (xtile, ytile) = tiles.Geo2Tile(geo_x, geo_y)
            msg = ('Expected tile (%f,%f) but got (%f,%f)'
                   % (expect_xtile, expect_ytile, xtile, ytile))
            self.assertAlmostEqual(expect_xtile, xtile, places=3, msg=msg)
            self.assertAlmostEqual(expect_ytile, ytile, places=3, msg=msg)

            # calculate where (.num_tiles_x/2,.num_tiles_x/2)(Tile) should be in geo coords, check
            expect_xtile = tiles.num_tiles_x/2.0
            expect_ytile = tiles.num_tiles_y/2.0
            geo_x = min_lon + (max_lon-min_lon)/2.0
            geo_y = min_lat + (max_lat-min_lat)/2.0
            (xtile, ytile) = tiles.Geo2Tile(geo_x, geo_y)
            msg = ('Expected tile (%f,%f) but got (%f,%f)'
                   % (expect_xtile, expect_ytile, xtile, ytile))
            self.assertAlmostEqual(expect_xtile, xtile, places=3, msg=msg)
            self.assertAlmostEqual(expect_ytile, ytile, places=3, msg=msg)

    app = wx.App()
    app_frame = AppFrame()
    app_frame.Show()
    app.MainLoop()

